keys:
   - &lorenz age14zcgmvkzkmccjf4jwrp4hhlww9qs600zdmyp8gar5djwh5yrg48sgvscpk
   - &wsl    age16yswachju798a8tr53ezsdrxfam3dstgag2g3mtv0jk7hfv6r9dqvekh2h
creation_rules:
  - path_regex: os/host/wsl/sops/[^/]+\.yaml$
    key_groups:
    - age:
      - *lorenz
      - *wsl
