seys:
  - &lorenz     age1c0g6s6daxy79dlm9uqczwlkh0hvjpghw5h8zzljc3vs275rvvqus30hv9l
  - &wsl        age16yswachju798a8tr53ezsdrxfam3dstgag2g3mtv0jk7hfv6r9dqvekh2h
  - &0mqr       age1k6udupm4ylkg3qgl096wytjj8m879r7qp02suhmsu27wdledr92se9kwqp
creation_rules:
  - path_regex: os/host/0mqr[^/]+/sops/[^/]+\.(yaml|json|bin)$
    key_groups:
    - age:
      - *lorenz
      - *0mqr
  - path_regex: os/host/wsl/sops/[^/]+\.yaml$
    key_groups:
    - age:
      - *lorenz
      - *wsl
  - path_regex: os/mixin/mkcert/sops/[^/]+\.yaml$
    key_groups:
    - age:
      - *lorenz
      - *0mqr
      - *wsl
  - path_regex: hm/profiles/sops/[^/]+\.yaml$
    key_groups:
    - age:
      - *lorenz
