#! /usr/bin/env bash

set -euo pipefail

if [ $# -lt 2 ]
then
	echo "Usage: cachix-push-flake CACHE-NAME INSTALLABLES..."
	exit 1
fi

nix build --json ${@:2} | jq -r '.[].outputs | to_entries[].value' | cachix push $1
