#! /usr/bin/env bash

set -xeuo pipefail

export RAD_HOME="/var/lib/radicle"

for GIT_DIR in "$RAD_HOME/storage"/*
do

export GIT_DIR
RID="$(basename $GIT_DIR)"
ID="$(mktemp -t "rad-id-$RID-XXXX.json")"

function config {
	sudo --preserve-env=GIT_DIR git config "$1" "${@:2}"
}

sudo --preserve-env=RAD_HOME --user radicle rad inspect --identity "$RID" > "$ID"

NAME="$(jq -r '.payload."xyz.radicle.project".name' "$ID")"

config cgit.clone-url "rid:${RID}"
config cgit.desc "$(jq -r '.payload."xyz.radicle.project".description' "$ID")"
config cgit.name "$NAME"
config cgit.defbranch "$(jq -r '.payload."xyz.radicle.project".defaultBranch' "$ID")"
config cgit.homepage "https://app.radicle.at/nodes/seed.radicle.at/rad:$RID"
config cgit.owner "$(jq -r '(if .threshold > 1 then "\(.threshold) of " else "" end) + (.delegates | sort | map(.[8:] | .[0:6] + "…" + .[-6:]) | join(", "))' "$ID")"
config cgit.snapshot-prefix "$NAME-$(jq -r --arg rid "$RID" '$rid | .[0:6] + "_" + .[-6:]' "$ID")"

done
