{
  lib,
  pkgs,
  ...
}:
with builtins; {
  imports = [
    ./terminal.nix
    ./rust.nix
    ../programs/bat
    ../programs/firefox
    ../programs/fzf.nix
    ../programs/gh.nix
    ../programs/git
    ../programs/go.nix
    ../programs/nvim
    ../programs/ripgrep.nix
    ../programs/ssh.nix
    ../programs/cakeml.nix
    ../services/mpris-proxy.nix
    ../services/syncthing.nix
  ];

  home.packages = with pkgs; let
    pythonPackages = python311Packages;
  in [
    alacritty
    aspell
    aspellDicts.en
    aspellDicts.en-computers
    aspellDicts.en-science
    asciinema
    autojump
    binutils
    brightnessctl
    cachix
    cmake
    curlFull
    dive
    docker-compose
    dos2unix
    elan
    elfutils
    entr
    envsubst
    exiftool
    exercism
    fd
    file
    fira
    fira-code
    fira-code-symbols
    fira-mono
    fontconfig
    font-awesome
    fzf
    gcc
    gdb
    ghcid
    glibcLocales
    gnumake
    google-cloud-sdk
    gource
    graphviz
    hlint
    htop
    iperf
    jq
    kbfs
    kdiff3
    kubectl
    liberation_ttf
    libreoffice
    llvm
    material-icons
    mupdf
    nmap
    ncdu
    neovim-remote
    niv
    nvme-cli
    nodejs
    nodePackages.pnpm
    noto-fonts
    pandoc
    pavucontrol
    pdfgrep
    pinta
    pythonPackages.python
    pythonPackages.beautifulsoup4
    pythonPackages.mwclient
    pythonPackages.pip
    pythonPackages.setuptools
    pythonPackages.requests
    pythonPackages.yamllint
    ranger
    shellcheck
    shfmt
    siji
    skaffold
    stow
    stylish-haskell
    sshfs-fuse
    universal-ctags
    monero-cli
    roboto-mono
    roboto-slab
    skopeo
    socat
    tio
    tmux
    tree
    wally-cli
    wget
    xclip
    xdotool
    yubikey-personalization
    yq
  ];
}
