{
  lib,
  pkgs,
  ...
}:
with builtins; {
  imports = [
    ./go.nix
    ./rust.nix
    ./terminal.nix

    ../programs/bat
    ../programs/fzf.nix
    ../programs/gh.nix
    ../programs/git
    ../programs/nvim
    ../programs/ripgrep.nix
    ../programs/ssh.nix
    ../services/syncthing.nix
  ];

  home.packages =
    (with pkgs.python3Packages; [
      python
      beautifulsoup4
      mwclient
      pip
      setuptools
      requests
      yamllint
    ])
    ++ (with pkgs; [
      aspell
      aspellDicts.en
      aspellDicts.en-computers
      aspellDicts.en-science
      asciinema
      autojump
      cachix
      cmake
      curlFull
      dive
      docker-compose
      dos2unix
      elan
      elfutils
      entr
      envsubst
      exiftool
      exercism
      fd
      file
      fira
      fira-code
      fira-code-symbols
      fira-mono
      fontconfig
      font-awesome
      fzf
      gcc
      gdb
      ghcid
      glibcLocales
      gnumake
      google-cloud-sdk
      gource
      graphviz
      hlint
      htop
      iperf
      jq
      kbfs
      kubectl
      liberation_ttf
      llvm
      material-icons
      mupdf
      nmap
      ncdu
      niv
      nvme-cli
      nodejs
      nodePackages.pnpm
      noto-fonts
      pandoc
      pavucontrol
      pdfgrep
      pinta
      ranger
      shellcheck
      shfmt
      siji
      skaffold
      stow
      stylish-haskell
      sshfs-fuse
      universal-ctags
      monero-cli
      roboto-mono
      roboto-slab
      skopeo
      socat
      tio
      tmux
      tree
      wally-cli
      wget
      yubikey-personalization
      yq
    ]);
}
