{
  lib,
  pkgs,
  config,
  osConfig,
  ...
}:
with builtins; {
  imports = [
    ./common.nix
    ./nixbuild.nix
    ./sops
    #../programs/docker.nix
    ../programs/atuin.nix
    ../programs/bat
    ../programs/direnv
    ../programs/fzf.nix
    ../programs/gh.nix
    ../programs/git
    ../programs/gpg.nix
    ../programs/jj.nix
    ../programs/nix
    ../programs/nvim
    ../programs/password-store.nix
    ../programs/ripgrep.nix
    ../programs/ssh.nix
    ../programs/tmux
    ../programs/zsh
    ../services/gpg-agent.nix
    #../services/syncthing.nix
  ];

  home.packages = with pkgs; [
    alejandra
    asciinema
    autojump
    beets
    cachix
    chromaprint
    csvkit
    curlFull
    dasel
    dateutils
    dnsutils
    docker-compose
    entr
    eza
    fatrace
    fd
    ffmpeg
    file
    fuse
    fzf
    glibcLocales
    graphviz
    htop
    iotop
    jq
    #kbfs
    miller
    moreutils
    mosh
    mtr
    ngrep
    ngrok
    neovim-remote
    niv
    nixpkgs-review
    nvme-cli
    openssl
    pandoc
    pantheon.elementary-files
    pantheon.elementary-photos
    parted
    pciutils
    pdfgrep
    pdftk
    phoronix-test-suite
    pinta
    poppler_utils
    psmisc
    pv
    pwgen
    rclone
    rmapi
    siji
    signal-cli
    skaffold
    sshfs-fuse
    universal-ctags
    usbutils
    tree
    unzip
    vmtouch
    xxHash
    yubikey-personalization
    yq
    zip
    zola
  ];
}
