name: dotfiles

on:
  workflow_dispatch:

jobs:
  dotfiles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: "nixpkgs=channel:nixos-unstable"
    - run: nix run nixpkgs#home-manager -- -v build --show-trace --impure --flake .#lorenz
    - run: |
        cp --verbose --dereference --recursive result/home-files dotfiles
        chmod ug+w dotfiles
        find dotfiles -type f -exec sed -i 's#/nix/store/[a-zA-Z0-9]*-[^/]*#…#g' {} \;
    - working-directory: dotfiles
      env:
        TOKEN: ${{ secrets.DOTFILES_TOKEN }}
      run: |
        git config --global user.email "542154+lorenzleutgeb@users.noreply.github.com"
        git config --global user.name "Lorenz Leutgeb"
        git init --initial-branch=main
        git add .
        git commit --message="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        git push --mirror https://token:$TOKEN@github.com/lorenzleutgeb/dotfiles.git
