name: dotfiles
on:
  - push
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "hi"
    - run: echo "debug? ${{ runner.debug && '--debug' }}"
    - run: "echo \"debug? $(if [ \\\"${FOO}\\\" = 'true' ]; then echo \\\"a\\\"; fi)\""
